"""
Django settings for game project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
'''
gmail
x0j00999@gmail.com
acbd1324
0936726488  

line
x0j009@163.com
acbd1324

admin
x0j009
acbd1324
https://baida.ddns.net/admin
baida9124753
x0j00999@gmail.com
jdshfsej54584848

x0j009@163.com
x0j00999

ngrok
x0j00999@gmail.com
acbd132413

linepay
860814    
0936726488  

NO-IP 
x0j00999@gmail.com
acbd1324
167.179.112.225

SSL
baida.ddns.net
Baida0936726488  
https://baida.ddns.net/callback     
http://192.168.1.108:8000/win_game/
ipconfig  cmd查詢ip

伺服器 Debian10
root
love860830

娛樂城
mvp777
mvp168

ss0905316743
qwepop123

Vultr
a0962087889@gmail.com  
Qwepop123123

python3 manage.py runserver 0.0.0.0:8080
python3 -m venv gamevenv  建立虛擬環境
. gamevenv/bin/activate 啟動虛擬環境
deactivate  離開虛擬環境win
source deactivate  離開虛擬環境linux
sudo fuser -k 8080/tcp
zhui975774quey@163.com
'''
#PS C:\Users\smile\win> python manage.py runserver 0.0.0.0:8000
#---------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wn#a7xr8^gna6rkhsxn#8!obwmcx@0^d4*3^6+)46rdd3akeb3'
LINE_CHANNEL_ACCESS_TOKEN = 'SJ0ehvLZrpvDYS0DnymOO1FJbE99ZGjoA55kX6htjKG/+PIj60ED4DA4q0PjW2WgXVoguhoo+T+bb4dku8tiFBkGbAm42sWakafpNrEpQvfDIwIoEapqi5/8M80ing9/gMQhbDSmIPFK6jBiP5TMqQdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = 'f950df46efc8d6111667d4dd4bbb1ea5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gamelinebot',
    'member_profile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]